In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

os.makedirs(
    "/content/drive/MyDrive/mutual-fund-dashboard/data/raw",
    exist_ok=True
)

print("Folder created!")

Folder created!

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Google AI Studio/01_fund_master.csv')
print(df.head())

   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

In [ ]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [ ]:
df.dtypes

amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

In [ ]:
df.describe()

,amfi_code,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount
count,40.000000,40.000000,40.000000,40.0,40.000000
mean,120247.000000,1.237000,0.812500,500.0,1277.500000
std,14534.998667,0.386584,0.387091,0.0,1082.847031
min,100016.000000,0.550000,0.000000,500.0,100.000000
25%,118632.750000,0.787500,1.000000,500.0,1000.000000
50%,119551.500000,1.425000,1.000000,500.0,1000.000000
75%,120842.250000,1.540000,1.000000,500.0,1000.000000
max,149324.000000,1.640000,1.000000,500.0,5000.000000

In [ ]:
df.shape

(40, 15)

In [ ]:
import requests
url="https://api.mfapi.in/mf/125497"
response=requests.get(url)
data=response.json()
print("Scheme Name:",data["meta"]["scheme_name"])
nav_df=pd.DataFrame(data["data"])
nav_df.head()

Scheme Name: SBI Small Cap Fund - Direct Plan - Growth

         date        nav
0  10-06-2026  193.43710
1  09-06-2026  194.38130
2  08-06-2026  191.90920
3  05-06-2026  194.75470
4  04-06-2026  194.52200

In [ ]:
nav_df.to_csv(
    "/content/drive/MyDrive/mutual-fund-dashboard/data/raw/hdfc_top100_nav.csv",
    index=False
)

In [ ]:
nav_df.to_csv("hdfc_top100_nav.csv", index=False)

In [ ]:
import requests
import os
folder = "/content/drive/MyDrive/mutual-fund-dashboard/data/raw"
os.makedirs(folder, exist_ok=True)

schemes = {
    "SBI_Bluechip": 119551,
    "ICICI_Bluechip": 120503,
    "Nippon_Large_Cap": 118632,
    "Axis_Bluechip": 119092,
    "Kotak_Bluechip": 120841
}

for scheme_name, scheme_id in schemes.items():

    url = f"https://api.mfapi.in/mf/{scheme_id}"

    response = requests.get(url)

    if response.status_code == 200:

        data = response.json()

        nav_df = pd.DataFrame(data["data"])

        file_name = f"{scheme_name}.csv"
        file_path = os.path.join(folder, file_name)

        nav_df.to_csv(file_path, index=False)

        print(f" Saved {file_name}")

 Saved SBI_Bluechip.csv
 Saved ICICI_Bluechip.csv
 Saved Nippon_Large_Cap.csv
 Saved Axis_Bluechip.csv
 Saved Kotak_Bluechip.csv

In [ ]:
import os

folder = "/content/drive/MyDrive/mutual-fund-dashboard/data/raw"

for file in os.listdir(folder):
    print(file)

hdfc_top100_nav.csv
SBI_Bluechip.csv
ICICI_Bluechip.csv
Nippon_Large_Cap.csv
Axis_Bluechip.csv
Kotak_Bluechip.csv

In [ ]:
print(df["fund_house"].unique)
print(df["fund_house"].nunique)

<bound method Series.unique of 0              SBI Mutual Fund
1              SBI Mutual Fund
2              SBI Mutual Fund
3              SBI Mutual Fund
4              SBI Mutual Fund
5             HDFC Mutual Fund
6             HDFC Mutual Fund
7             HDFC Mutual Fund
8             HDFC Mutual Fund
9             HDFC Mutual Fund
10         ICICI Prudential MF
11         ICICI Prudential MF
12         ICICI Prudential MF
13         ICICI Prudential MF
14         ICICI Prudential MF
15             Nippon India MF
16             Nippon India MF
17             Nippon India MF
18             Nippon India MF
19             Nippon India MF
20           Kotak Mahindra MF
21           Kotak Mahindra MF
22           Kotak Mahindra MF
23           Kotak Mahindra MF
24            Axis Mutual Fund
25            Axis Mutual Fund
26            Axis Mutual Fund
27            Axis Mutual Fund
28    Aditya Birla Sun Life MF
29    Aditya Birla Sun Life MF
30    Aditya Birla Sun Life MF
31             UTI Mutual Fund
32             UTI Mutual Fund
33             UTI Mutual Fund
34              Mirae Asset MF
35              Mirae Asset MF
36              Mirae Asset MF
37             DSP Mutual Fund
38             DSP Mutual Fund
39             DSP Mutual Fund
Name: fund_house, dtype: object>
<bound method IndexOpsMixin.nunique of 0              SBI Mutual Fund
1              SBI Mutual Fund
2              SBI Mutual Fund
3              SBI Mutual Fund
4              SBI Mutual Fund
5             HDFC Mutual Fund
6             HDFC Mutual Fund
7             HDFC Mutual Fund
8             HDFC Mutual Fund
9             HDFC Mutual Fund
10         ICICI Prudential MF
11         ICICI Prudential MF
12         ICICI Prudential MF
13         ICICI Prudential MF
14         ICICI Prudential MF
15             Nippon India MF
16             Nippon India MF
17             Nippon India MF
18             Nippon India MF
19             Nippon India MF
20           Kotak Mahindra MF
21           Kotak Mahindra MF
22           Kotak Mahindra MF
23           Kotak Mahindra MF
24            Axis Mutual Fund
25            Axis Mutual Fund
26            Axis Mutual Fund
27            Axis Mutual Fund
28    Aditya Birla Sun Life MF
29    Aditya Birla Sun Life MF
30    Aditya Birla Sun Life MF
31             UTI Mutual Fund
32             UTI Mutual Fund
33             UTI Mutual Fund
34              Mirae Asset MF
35              Mirae Asset MF
36              Mirae Asset MF
37             DSP Mutual Fund
38             DSP Mutual Fund
39             DSP Mutual Fund
Name: fund_house, dtype: object>

In [ ]:
print(df["category"].unique)

<bound method Series.unique of 0     Equity
1     Equity
2     Equity
3     Equity
4       Debt
5     Equity
6     Equity
7     Equity
8     Equity
9       Debt
10    Equity
11    Equity
12    Equity
13    Equity
14      Debt
15    Equity
16    Equity
17    Equity
18    Equity
19      Debt
20    Equity
21    Equity
22    Equity
23      Debt
24    Equity
25    Equity
26    Equity
27    Equity
28    Equity
29    Equity
30      Debt
31    Equity
32    Equity
33    Equity
34    Equity
35    Equity
36    Equity
37    Equity
38    Equity
39    Equity
Name: category, dtype: object>

In [ ]:
print(df["sub_category"].unique())

['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

In [ ]:
print(df["risk_category"].unique())

['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [ ]:
print(df["fund_house"].value_counts)

<bound method IndexOpsMixin.value_counts of 0              SBI Mutual Fund
1              SBI Mutual Fund
2              SBI Mutual Fund
3              SBI Mutual Fund
4              SBI Mutual Fund
5             HDFC Mutual Fund
6             HDFC Mutual Fund
7             HDFC Mutual Fund
8             HDFC Mutual Fund
9             HDFC Mutual Fund
10         ICICI Prudential MF
11         ICICI Prudential MF
12         ICICI Prudential MF
13         ICICI Prudential MF
14         ICICI Prudential MF
15             Nippon India MF
16             Nippon India MF
17             Nippon India MF
18             Nippon India MF
19             Nippon India MF
20           Kotak Mahindra MF
21           Kotak Mahindra MF
22           Kotak Mahindra MF
23           Kotak Mahindra MF
24            Axis Mutual Fund
25            Axis Mutual Fund
26            Axis Mutual Fund
27            Axis Mutual Fund
28    Aditya Birla Sun Life MF
29    Aditya Birla Sun Life MF
30    Aditya Birla Sun Life MF
31             UTI Mutual Fund
32             UTI Mutual Fund
33             UTI Mutual Fund
34              Mirae Asset MF
35              Mirae Asset MF
36              Mirae Asset MF
37             DSP Mutual Fund
38             DSP Mutual Fund
39             DSP Mutual Fund
Name: fund_house, dtype: object>

In [ ]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [ ]:
fund_codes = set(df["amfi_code"].unique())
print(fund_codes)

{np.int64(119552), np.int64(120841), np.int64(120842), np.int64(120843), np.int64(120844), np.int64(119598), np.int64(119599), np.int64(100016), np.int64(119092), np.int64(119093), np.int64(119094), np.int64(120503), np.int64(120504), np.int64(100025), np.int64(120506), np.int64(120505), np.int64(125497), np.int64(125498), np.int64(120507), np.int64(119095), np.int64(100033), np.int64(149322), np.int64(149323), np.int64(149324), np.int64(119120), np.int64(101206), np.int64(101207), np.int64(101208), np.int64(148567), np.int64(148568), np.int64(148569), np.int64(102885), np.int64(102886), np.int64(102887), np.int64(118632), np.int64(118633), np.int64(118634), np.int64(118635), np.int64(118636), np.int64(119551)}

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/Google AI Studio/01_fund_master_clean.csv",
    index=False
)

In [ ]:
dg=pd.read_csv("/content/drive/MyDrive/Google AI Studio/02_nav_history.csv")
dg.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [ ]:
nav_codes=set(dg["amfi_code"].unique())
print(nav_codes)

{np.int64(119552), np.int64(120841), np.int64(120842), np.int64(120843), np.int64(120844), np.int64(119598), np.int64(119599), np.int64(100016), np.int64(119092), np.int64(119093), np.int64(119094), np.int64(119095), np.int64(120503), np.int64(100025), np.int64(120504), np.int64(120505), np.int64(120506), np.int64(120507), np.int64(125497), np.int64(125498), np.int64(100033), np.int64(149322), np.int64(149323), np.int64(149324), np.int64(119120), np.int64(101206), np.int64(101207), np.int64(101208), np.int64(148567), np.int64(148568), np.int64(148569), np.int64(102885), np.int64(102886), np.int64(102887), np.int64(118632), np.int64(118633), np.int64(118634), np.int64(118635), np.int64(118636), np.int64(119551)}

In [ ]:
dg["date"]=pd.to_datetime(dg["date"],errors='coerce')

In [ ]:
dg["date"].isnull().sum()

np.int64(27842)

In [ ]:
before=len(dg)
dg=dg.drop_duplicates()
after=len(dg)
print("no of removed",after-before)

no of removed 0

In [ ]:
dg=dg.sort_values(["amfi_code","date"])

In [ ]:
dg["nav"]=pd.to_numeric(dg["nav"],errors="coerce")

In [ ]:
dg["nav"]=dg.groupby("amfi_code")["nav"].ffill()

In [ ]:
unvalid=dg[dg["nav"]<=0]
print(len(unvalid))

0

In [ ]:
print(dg.duplicated().sum())

0

In [ ]:
print(dg["date"].isnull().sum())

27842

In [ ]:
print(dg["nav"].isnull().sum())

0

In [ ]:
dg[dg["date"].isnull()].head(20)

      amfi_code date       nav
5758     100016  NaT  510.2445
5759     100016  NaT  514.3636
5760     100016  NaT  514.7627
5761     100016  NaT  517.3803
5762     100016  NaT  513.1866
5763     100016  NaT  507.1294
5764     100016  NaT  507.8710
5765     100016  NaT  506.7062
5766     100016  NaT  509.7762
5767     100016  NaT  509.6800
5768     100016  NaT  510.8661
5769     100016  NaT  503.8641
5770     100016  NaT  512.5903
5780     100016  NaT  507.5435
5781     100016  NaT  504.7492
5782     100016  NaT  507.0506
5783     100016  NaT  516.7872
5784     100016  NaT  516.4246
5785     100016  NaT  519.3918
5786     100016  NaT  519.1698

In [ ]:

raw_df = pd.read_csv("/content/drive/MyDrive/Google AI Studio/02_nav_history.csv")

print(raw_df["date"].head(20))

0     2022-01-03
1     2022-01-04
2     2022-01-05
3     2022-01-06
4     2022-01-07
5     2022-01-10
6     2022-01-11
7     2022-01-12
8     2022-01-13
9     2022-01-14
10    2022-01-17
11    2022-01-18
12    2022-01-19
13    2022-01-20
14    2022-01-21
15    2022-01-24
16    2022-01-25
17    2022-01-26
18    2022-01-27
19    2022-01-28
Name: date, dtype: object

In [ ]:
print(raw_df["date"].isnull().sum())

0

In [ ]:
print(dg["date"].dtype)
print(dg["date"].head())

datetime64[ns]
5771   2022-01-02
5791   2022-01-03
5814   2022-01-04
5857   2022-01-06
5879   2022-01-07
Name: date, dtype: datetime64[ns]

In [ ]:
print(dg["date"].isna().sum())

27842

In [ ]:
print(dg.isnull().sum())

amfi_code        0
date         27842
nav              0
dtype: int64

In [ ]:
raw_dg = pd.read_csv("/content/drive/MyDrive/Google AI Studio/02_nav_history.csv")

print(raw_dg["date"].isna().sum())

0

In [ ]:
raw_dg = pd.read_csv("/content/drive/MyDrive/Google AI Studio/02_nav_history.csv")

converted = pd.to_datetime(raw_dg["date"], errors="coerce")

bad_rows = raw_dg[converted.isna()]

print("Bad rows:", len(bad_rows))
print(bad_rows["date"].head(50))

Bad rows: 0
Series([], Name: date, dtype: object)

In [ ]:
print(raw_dg["date"].sample(30).tolist())

['2026-03-03', '2022-02-11', '2024-04-05', '2022-04-13', '2023-05-24', '2023-12-11', '2025-07-23', '2024-07-16', '2025-11-05', '2023-02-17', '2022-04-28', '2023-09-13', '2024-07-10', '2022-10-31', '2023-04-27', '2022-10-10', '2023-05-12', '2025-09-11', '2022-08-05', '2022-12-01', '2023-10-31', '2024-03-21', '2023-03-13', '2024-08-14', '2025-01-27', '2022-03-01', '2023-05-17', '2025-12-26', '2024-01-16', '2024-09-20']

In [ ]:
print(dg.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [ ]:
dg["date"] = pd.to_datetime(
    raw_dg["date"],
    format="mixed",
    errors="coerce"
)

In [ ]:
dg.to_csv(
    "/content/drive/MyDrive/Google AI Studio/nav_history_clean.csv",
    index=False
)

In [ ]:
import pandas as pd
dt=pd.read_csv("/content/drive/MyDrive/Google AI Studio/08_investor_transactions.csv")
dt.head(5)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [ ]:
dt["transaction_date"] = pd.to_datetime(
    dt["transaction_date"],
    errors="coerce"
)

In [ ]:
dt.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [ ]:
dt["kyc_status"].unique()

array(['Verified', 'Pending'], dtype=object)

In [ ]:
import pandas as pd
ds=pd.read_csv("/content/drive/MyDrive/Google AI Studio/07_scheme_performance.csv")

In [ ]:
print(ds.columns)
print(ds.head())

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

In [ ]:
return_cols=['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade']

In [ ]:
for col in return_cols:
     ds[col]=pd.to_numeric(ds[col],errors='coerce')

In [ ]:
invalid=ds[ds[return_cols].isna().any(axis=1)]
print(len(invalid))
invalid.head()

40

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,NaN,NaN,NaN,NaN,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,NaN
1,119552,NaN,NaN,NaN,NaN,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,NaN
2,119598,NaN,NaN,NaN,NaN,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,NaN
3,119599,NaN,NaN,NaN,NaN,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,NaN
4,119120,NaN,NaN,NaN,NaN,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,NaN

In [ ]:
ds[return_cols].isnull().sum()

amfi_code              0
scheme_name           40
fund_house            40
category              40
plan                  40
return_1yr_pct         0
return_3yr_pct         0
return_5yr_pct         0
benchmark_3yr_pct      0
alpha                  0
beta                   0
sharpe_ratio           0
sortino_ratio          0
std_dev_ann_pct        0
max_drawdown_pct       0
aum_crore              0
expense_ratio_pct      0
morningstar_rating     0
risk_grade            40
dtype: int64

In [ ]:
print(type(return_cols))

<class 'list'>

In [ ]:
ds.dropna(how='all')
ds.isnull().sum()

amfi_code              0
scheme_name           40
fund_house            40
category              40
plan                  40
return_1yr_pct         0
return_3yr_pct         0
return_5yr_pct         0
benchmark_3yr_pct      0
alpha                  0
beta                   0
sharpe_ratio           0
sortino_ratio          0
std_dev_ann_pct        0
max_drawdown_pct       0
aum_crore              0
expense_ratio_pct      0
morningstar_rating     0
risk_grade            40
dtype: int64

In [ ]:
expense_issue=ds[(ds["expense_ratio_pct"] < 0.1) |
  (ds["expense_ratio_pct"]>2.5)
]
print(len(expense_issue))

0

In [ ]:
for col in ["return_1yr_pct","return_3yr_pct","return_5yr_pct"]:
  print(col)
  print("Min=",ds[col].min())
  print("Max",ds[col].max())

return_1yr_pct
Min= 4.26
Max 24.93
return_3yr_pct
Min= 5.14
Max 23.39
return_5yr_pct
Min= 5.43
Max 23.8

In [ ]:
return_anomalies = ds[
    (ds["return_1yr_pct"] < -100) |
    (ds["return_1yr_pct"] > 100) |
    (ds["return_3yr_pct"] < -100) |
    (ds["return_3yr_pct"] > 100) |
    (ds["return_5yr_pct"] < -100) |
    (ds["return_5yr_pct"] > 100)
]

print(len(return_anomalies))

0

In [ ]:
ds[return_cols].describe()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
count,40.000000,0.0,0.0,0.0,0.0,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000,0.0
mean,120247.000000,NaN,NaN,NaN,NaN,14.376000,14.089000,14.516750,12.835500,1.253500,0.873250,1.361750,2.082500,14.962500,-19.200250,26091.60000,1.237000,4.250000,NaN
std,14534.998667,NaN,NaN,NaN,NaN,4.883023,4.617253,4.454021,4.740972,0.447412,0.224846,1.475805,2.203144,6.669282,8.819164,13809.11134,0.386584,0.742484,NaN
min,100016.000000,NaN,NaN,NaN,NaN,4.260000,5.140000,5.430000,3.960000,0.510000,0.220000,0.800000,1.030000,0.500000,-33.500000,979.00000,0.550000,3.000000,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,11.735000,12.035000,12.340000,10.690000,0.887500,0.890000,0.865000,1.270000,14.000000,-25.062500,17400.50000,0.787500,4.000000,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,14.620000,14.205000,14.185000,13.090000,1.205000,0.960000,0.925000,1.445000,14.000000,-20.600000,26713.00000,1.425000,4.000000,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,16.392500,15.882500,17.585000,14.775000,1.700000,1.000000,0.985000,1.637500,19.000000,-14.255000,38125.00000,1.540000,5.000000,NaN
max,149324.000000,NaN,NaN,NaN,NaN,24.930000,23.390000,23.800000,22.160000,1.980000,1.040000,7.680000,10.370000,25.000000,-2.230000,49046.00000,1.640000,5.000000,NaN

In [ ]:
beta_issue=ds[
    (ds["beta"]<0)|
    (ds["beta"]>3)
]
print(len(beta_issue))

0

In [ ]:
sharpe_issue = ds[
    (ds["sharpe_ratio"] < -5) |
    (ds["sharpe_ratio"] > 10)
]

print( len(sharpe_issue))

0

In [ ]:
drawdown_issue = ds[
    (ds["max_drawdown_pct"] > 0) |
    (ds["max_drawdown_pct"] < -100)
]

print(len(drawdown_issue))

0

In [ ]:
ds["anomaly_flag"] = (
    (ds["expense_ratio_pct"] < 0.1) |
    (ds["expense_ratio_pct"] > 2.5) |
    (ds["beta"] < 0) |
    (ds["beta"] > 3) |
    (ds["max_drawdown_pct"] > 0) |
    (ds["max_drawdown_pct"] < -100)
)

In [ ]:
print(ds['anomaly_flag'].sum())

0

In [ ]:
ds.to_csv(
    "/content/drive/MyDrive/Google AI Studio/07_scheme_performance_clean.csv"
,
    index=False
)